print(127**(1/3))
nome = input("qual é o seu nome? ")
print("Prazer em te conhecer {:>20}!".format(nome))
print("Prazer em te conhecer {:<20}!".format(nome))
print("Prazer em te conhecer {:^20}!".format(nome))
print("Prazer em te concern {:=^20}!".format(nome))